import { MediaPlayer } from "./MediaPlayer";

const player = new MediaPlayer();

player.pressPlay(); // Starting playback...
player.pressPlay(); // Pausing playback...
player.pressPlay(); // Resuming playback...
player.pressPlay(); // Pausing playback...