worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    server {
        listen 80;

        location = /urls {
            if ($request_method = POST) {
                proxy_pass http://write-service:8001;
                break;
            }
        }

        # location /urls {
        #     if ($request_method = GET) {
        #         proxy_pass http://read-service:8002;
        #         break;
        #     }
        # }

        location / {
            return 404;
        }
    }
}
