version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitly
    ports:
      - "5432:5432"

  write-service:
    build: ./write-service
    container_name: write-service
    volumes:
      - ./write-service:/app
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: redis://redis:6379
      PG_URL: postgres://user:password@postgres:5432/bitly
    ports:
      - "8001:8001"

  read-service:
    build: ./read-service
    container_name: read-service
    volumes:
      - ./read-service:/app
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_URL: redis://redis:6379
      PG_URL: postgres://user:password@postgres:5432/bitly
    ports:
      - "8002:8002"

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - write-service
      - read-service
